# Basic Information 
title: Hyobin Kim
position: Researcher
affiliation: Seoul National University Hospital
email: hyobinkim (at) gmail.com

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Hyobin Kim, Hyo, Hyobin, Kim, Seoul National University Hospital, Seoul National University, Seoul, Korea, hyobin, hyobinkim, hyobin kim, hyobin k
description: Hyobin Kim's personal website
canonical: https://rose2gyqls.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=qsj2rUcAAAAJ&hl=ko
cv_link: assets/files/hyobin_cv.pdf
github_link: https://github.com/rose2gyqls
linkedin: https://www.linkedin.com/in/hyobin-kim-0993ab1b1/
# twitter: https://twitter.com/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
# google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# Site URL (for sitemap and SEO)
url: https://rose2gyqls.github.io

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/

# Navigation
nav:
  - name: Home
    url: /
  - name: Publications
    url: /publications.html
  - name: Experiences
    url: /experiences.html
  - name: CV
    url: /cv.html

# Plugins
plugins:
  - jekyll-sitemap
